// Reviewed files from the existing frontend. New images/styles are private to
// the repository until explicitly added here; no recursive asset-folder upload.
// This manifest is build input only and must never be copied to dist.
export const publicAssetFiles = Object.freeze([
    'assets/favicon.ico',
    'assets/img/footer-logo.svg',
    'assets/img/header-bg.png',
    'assets/img/map-image.png',
    'assets/img/navbar-logo.svg',
    'assets/img/landing/hero-product-desktop.png',
    'assets/img/landing/hero-product-mobile.png',
    'assets/img/landing/nero_logo.svg',
    'assets/img/landing/portfolio-1.png',
    'assets/img/landing/portfolio-2.png',
    'assets/img/landing/portfolio-3.png',
    'assets/img/landing/portfolio-4.png',
    'assets/img/landing/portfolio-5.png',
    'assets/img/partner/logo_list_1.png',
    'assets/img/partner/logo_list_2.png',
    'assets/img/partner/logo_list_3.png',
    'assets/img/partner/logo_list_4.png',
    'assets/img/partner/logo_list_5.png',
    'assets/img/partner/logo_list_6.png',
    'assets/img/partner/logo_list_7.png',
    'assets/img/services/appstore.png',
    'assets/img/services/nero_mock.png',
    'assets/img/services/playstore.png',
    'css/about.css',
    'css/announcement.css',
    'css/landing.css',
    'css/modal.css',
    'css/services.css',
    'css/styles.css',
]);
